// All 57 participating user groups
export const USER_GROUPS = [
  { flag: "🇪🇸", name: "AWS Barcelona User Group", city: "Barcelona, Spain" },
  { flag: "🇬🇧", name: "AWS Leeds User Group", city: "Leeds, United Kingdom" },
  { flag: "🇫🇮", name: "AWS Meetup JKL", city: "Jyväskylä, Finland" },
  { flag: "🇨🇭", name: "AWS Swiss UG – Lausanne", city: "Lausanne, Switzerland" },
  { flag: "🇨🇭", name: "AWS Swiss UG – Zürich", city: "Zürich, Switzerland" },
  { flag: "🇨🇭", name: "AWS Swiss UG – Geneva", city: "Geneva, Switzerland" },
  { flag: "🇷🇴", name: "AWS Transylvania Cloud", city: "Cluj-Napoca, Romania" },
  { flag: "🇵🇱", name: "AWS User Group 3City", city: "Gdansk, Poland" },
  { flag: "🇪🇸", name: "AWS UG Asturias", city: "Oviedo, Spain" },
  { flag: "🇬🇷", name: "AWS User Group Athens", city: "Athens, Greece" },
  { flag: "🇧🇪", name: "AWS User Group Belgium", city: "Brussels, Belgium" },
  { flag: "🇩🇪", name: "AWS User Group Bonn", city: "Bonn, Germany" },
  { flag: "🇭🇺", name: "AWS User Group Budapest", city: "Budapest, Hungary" },
  { flag: "🇩🇪", name: "AWS User Group Cologne", city: "Köln, Germany" },
  { flag: "🇮🇹", name: "AWS User Group Cuneo", city: "Cuneo, Italy" },
  { flag: "🇩🇪", name: "AWS User Group Dortmund", city: "Dortmund, Germany" },
  { flag: "🇫🇮", name: "AWS User Group Finland", city: "Helsinki, Finland" },
  { flag: "🇫🇷", name: "AWS UG France – Paris", city: "Paris, France" },
  { flag: "🇪🇸", name: "AWS UG Galicia", city: "Santiago de Compostela, Spain" },
  { flag: "🇮🇹", name: "AWS User Group Genova", city: "Genova, Italy" },
  { flag: "🇩🇪", name: "AWS User Group Hannover", city: "Hannover, Germany" },
  { flag: "🇳🇴", name: "AWS UG Innlandet", city: "Hamar, Norway" },
  { flag: "🇹🇷", name: "AWS User Group Istanbul", city: "Istanbul, Turkey" },
  { flag: "🇺🇦", name: "AWS UG Ivano-Frankivsk", city: "Ivano-Frankivsk, Ukraine" },
  { flag: "🇫🇮", name: "AWS User Group Kuopio", city: "Kuopio, Finland" },
  { flag: "🇸🇮", name: "AWS UG Ljubljana", city: "Ljubljana, Slovenia" },
  { flag: "🇲🇰", name: "AWS UG Macedonia", city: "Skopje, Macedonia" },
  { flag: "🇪🇸", name: "AWS User Group Malaga", city: "Malaga, Spain" },
  { flag: "🇲🇩", name: "AWS UG Moldova", city: "Chisinau, Moldova" },
  { flag: "🇲🇪", name: "AWS UG Montenegro", city: "Podgorica, Montenegro" },
  { flag: "🇩🇪", name: "AWS User Group Munich", city: "München, Germany" },
  { flag: "🇩🇪", name: "AWS UG Münsterland", city: "Münster, Germany" },
  { flag: "🇮🇹", name: "AWS User Group Napoli", city: "Naples, Italy" },
  { flag: "🇩🇪", name: "AWS UG Nürnberg", city: "Nürnberg, Germany" },
  { flag: "🇳🇴", name: "AWS UG Oslo", city: "Oslo, Norway" },
  { flag: "🇮🇹", name: "AWS User Group Pavia", city: "Pavia, Italy" },
  { flag: "🇮🇹", name: "AWS User Group Roma", city: "Roma, Italy" },
  { flag: "🇮🇹", name: "AWS User Group Salerno", city: "Salerno, Italy" },
  { flag: "🇧🇦", name: "AWS UG Sarajevo", city: "Sarajevo, Bosnia & Herzegovina" },
  { flag: "🇸🇪", name: "AWS UG Skåne", city: "Malmö, Sweden" },
  { flag: "🇫🇮", name: "AWS UG Tampere", city: "Tampere, Finland" },
  { flag: "🇨🇭", name: "AWS UG Ticino", city: "Lugano, Switzerland" },
  { flag: "🇷🇴", name: "AWS UG Timisoara", city: "Timisoara, Romania" },
  { flag: "🇮🇹", name: "AWS UG Venezia", city: "Venice, Italy" },
  { flag: "🇦🇹", name: "AWS User Group Vienna", city: "Vienna, Austria" },
  { flag: "🇵🇱", name: "AWS UG Warsaw", city: "Warsaw, Poland" },
  { flag: "🇬🇧", name: "AWS UG West Midlands", city: "Birmingham, United Kingdom" },
  { flag: "🇮🇹", name: "AWS Well-Architected UG Italy", city: "Milano, Italy" },
  { flag: "🇩🇪", name: "AWS Women's UG Munich", city: "Munich, Germany" },
  { flag: "🇩🇪", name: "Berlin AWS User Group", city: "Berlin, Germany" },
  { flag: "🇷🇴", name: "Bucharest AWS User Group", city: "Bucharest, Romania" },
  { flag: "🇩🇪", name: "Dresden AWS User Group", city: "Dresden, Germany" },
  { flag: "🇩🇪", name: "Frankfurt AWS User Group", city: "Frankfurt, Germany" },
  { flag: "🇫🇷", name: "Grenoble AWS User Group", city: "Grenoble, France" },
  { flag: "🇩🇪", name: "Leipzig AWS User Group", city: "Leipzig, Germany" },
  { flag: "🇫🇷", name: "Lille AWS User Group", city: "Lille, France" },
  { flag: "🇫🇷", name: "Poitiers AWS User Group", city: "Poitiers, France" },
];

export const COUNTRIES = Array.from(new Set(USER_GROUPS.map((g) => g.flag)));
